package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aplicacion generated by hbm2java
 */
@Entity
@Table(name="aplicacion"
    ,catalog="gestor_versiones"
    , uniqueConstraints = {@UniqueConstraint(columnNames="nombreAplicacion"), @UniqueConstraint(columnNames="nombreEjecutableApp")} 
)
public class Aplicacion  implements java.io.Serializable {


     private Integer pkIdAplicacion;
     private String nombreAplicacion;
     private String descripcionAplicacion;
     private Integer numEjecNoPermitidas;
     private String nombreEjecutableApp;
     private Set usuarioTieneAplicacions = new HashSet(0);
     private Set archivoConfiguracions = new HashSet(0);

    public Aplicacion() {
    }

	
    public Aplicacion(String nombreAplicacion, String descripcionAplicacion, String nombreEjecutableApp) {
        this.nombreAplicacion = nombreAplicacion;
        this.descripcionAplicacion = descripcionAplicacion;
        this.nombreEjecutableApp = nombreEjecutableApp;
    }
    public Aplicacion(String nombreAplicacion, String descripcionAplicacion, Integer numEjecNoPermitidas, String nombreEjecutableApp, Set usuarioTieneAplicacions, Set archivoConfiguracions) {
       this.nombreAplicacion = nombreAplicacion;
       this.descripcionAplicacion = descripcionAplicacion;
       this.numEjecNoPermitidas = numEjecNoPermitidas;
       this.nombreEjecutableApp = nombreEjecutableApp;
       this.usuarioTieneAplicacions = usuarioTieneAplicacions;
       this.archivoConfiguracions = archivoConfiguracions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_idAplicacion", unique=true, nullable=false)
    public Integer getPkIdAplicacion() {
        return this.pkIdAplicacion;
    }
    
    public void setPkIdAplicacion(Integer pkIdAplicacion) {
        this.pkIdAplicacion = pkIdAplicacion;
    }

    
    @Column(name="nombreAplicacion", unique=true, nullable=false, length=45)
    public String getNombreAplicacion() {
        return this.nombreAplicacion;
    }
    
    public void setNombreAplicacion(String nombreAplicacion) {
        this.nombreAplicacion = nombreAplicacion;
    }

    
    @Column(name="descripcionAplicacion", nullable=false, length=45)
    public String getDescripcionAplicacion() {
        return this.descripcionAplicacion;
    }
    
    public void setDescripcionAplicacion(String descripcionAplicacion) {
        this.descripcionAplicacion = descripcionAplicacion;
    }

    
    @Column(name="numEjecNoPermitidas")
    public Integer getNumEjecNoPermitidas() {
        return this.numEjecNoPermitidas;
    }
    
    public void setNumEjecNoPermitidas(Integer numEjecNoPermitidas) {
        this.numEjecNoPermitidas = numEjecNoPermitidas;
    }

    
    @Column(name="nombreEjecutableApp", unique=true, nullable=false, length=20)
    public String getNombreEjecutableApp() {
        return this.nombreEjecutableApp;
    }
    
    public void setNombreEjecutableApp(String nombreEjecutableApp) {
        this.nombreEjecutableApp = nombreEjecutableApp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aplicacion")
    public Set getUsuarioTieneAplicacions() {
        return this.usuarioTieneAplicacions;
    }
    
    public void setUsuarioTieneAplicacions(Set usuarioTieneAplicacions) {
        this.usuarioTieneAplicacions = usuarioTieneAplicacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aplicacion")
    public Set getArchivoConfiguracions() {
        return this.archivoConfiguracions;
    }
    
    public void setArchivoConfiguracions(Set archivoConfiguracions) {
        this.archivoConfiguracions = archivoConfiguracions;
    }




}


