package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ArchivoConfiguracion generated by hbm2java
 */
@Entity
@Table(name="archivo_configuracion"
    ,catalog="gestor_versiones"
    , uniqueConstraints = {@UniqueConstraint(columnNames="directorioArchivo"), @UniqueConstraint(columnNames="nombreArchivo")} 
)
public class ArchivoConfiguracion  implements java.io.Serializable {


     private Integer pkIdArchivoConfiguracion;
     private Aplicacion aplicacion;
     private String nombreArchivo;
     private String descripcionArchivo;
     private String directorioArchivo;
     private Set novedadActualizacionApps = new HashSet(0);

    public ArchivoConfiguracion() {
        this.aplicacion = new Aplicacion();
    }

	
    public ArchivoConfiguracion(Aplicacion aplicacion, String nombreArchivo, String directorioArchivo) {
        this.aplicacion = aplicacion;
        this.nombreArchivo = nombreArchivo;
        this.directorioArchivo = directorioArchivo;
    }
    public ArchivoConfiguracion(Aplicacion aplicacion, String nombreArchivo, String descripcionArchivo, String directorioArchivo, Set novedadActualizacionApps) {
       this.aplicacion = aplicacion;
       this.nombreArchivo = nombreArchivo;
       this.descripcionArchivo = descripcionArchivo;
       this.directorioArchivo = directorioArchivo;
       this.novedadActualizacionApps = novedadActualizacionApps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_idArchivoConfiguracion", unique=true, nullable=false)
    public Integer getPkIdArchivoConfiguracion() {
        return this.pkIdArchivoConfiguracion;
    }
    
    public void setPkIdArchivoConfiguracion(Integer pkIdArchivoConfiguracion) {
        this.pkIdArchivoConfiguracion = pkIdArchivoConfiguracion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_archivoConfig_aplicacion", nullable=false)
    public Aplicacion getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(Aplicacion aplicacion) {
        this.aplicacion = aplicacion;
    }

    
    @Column(name="nombreArchivo", unique=true, nullable=false, length=45)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    
    @Column(name="descripcionArchivo", length=45)
    public String getDescripcionArchivo() {
        return this.descripcionArchivo;
    }
    
    public void setDescripcionArchivo(String descripcionArchivo) {
        this.descripcionArchivo = descripcionArchivo;
    }

    
    @Column(name="directorioArchivo", unique=true, nullable=false, length=200)
    public String getDirectorioArchivo() {
        return this.directorioArchivo;
    }
    
    public void setDirectorioArchivo(String directorioArchivo) {
        this.directorioArchivo = directorioArchivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="archivoConfiguracion")
    public Set getNovedadActualizacionApps() {
        return this.novedadActualizacionApps;
    }
    
    public void setNovedadActualizacionApps(Set novedadActualizacionApps) {
        this.novedadActualizacionApps = novedadActualizacionApps;
    }




}


