package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NovedadActualizacionApp generated by hbm2java
 */
@Entity
@Table(name="novedad_actualizacion_app"
    ,catalog="gestor_versiones"
)
public class NovedadActualizacionApp  implements java.io.Serializable {


     private Integer pkIdNovedadActualizacionApp;
     private ArchivoConfiguracion archivoConfiguracion;
     private Date fechaActualizacionAplicacion;
     private String descripcionNovedadActualizacion;
     private String descripcionDosNovedad;
     private String usuarioRegActualizacion;

    public NovedadActualizacionApp() {
        this.archivoConfiguracion = new ArchivoConfiguracion();
    }

	
    public NovedadActualizacionApp(ArchivoConfiguracion archivoConfiguracion, Date fechaActualizacionAplicacion, String descripcionNovedadActualizacion) {
        this.archivoConfiguracion = archivoConfiguracion;
        this.fechaActualizacionAplicacion = fechaActualizacionAplicacion;
        this.descripcionNovedadActualizacion = descripcionNovedadActualizacion;
    }
    public NovedadActualizacionApp(ArchivoConfiguracion archivoConfiguracion, Date fechaActualizacionAplicacion, String descripcionNovedadActualizacion, String descripcionDosNovedad, String usuarioRegActualizacion) {
       this.archivoConfiguracion = archivoConfiguracion;
       this.fechaActualizacionAplicacion = fechaActualizacionAplicacion;
       this.descripcionNovedadActualizacion = descripcionNovedadActualizacion;
       this.descripcionDosNovedad = descripcionDosNovedad;
       this.usuarioRegActualizacion = usuarioRegActualizacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_idNovedadActualizacionApp", unique=true, nullable=false)
    public Integer getPkIdNovedadActualizacionApp() {
        return this.pkIdNovedadActualizacionApp;
    }
    
    public void setPkIdNovedadActualizacionApp(Integer pkIdNovedadActualizacionApp) {
        this.pkIdNovedadActualizacionApp = pkIdNovedadActualizacionApp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_novedadActu_ArchConfig", nullable=false)
    public ArchivoConfiguracion getArchivoConfiguracion() {
        return this.archivoConfiguracion;
    }
    
    public void setArchivoConfiguracion(ArchivoConfiguracion archivoConfiguracion) {
        this.archivoConfiguracion = archivoConfiguracion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaActualizacionAplicacion", nullable=false, length=19)
    public Date getFechaActualizacionAplicacion() {
        return this.fechaActualizacionAplicacion;
    }
    
    public void setFechaActualizacionAplicacion(Date fechaActualizacionAplicacion) {
        this.fechaActualizacionAplicacion = fechaActualizacionAplicacion;
    }

    
    @Column(name="descripcionNovedadActualizacion", nullable=false, length=150)
    public String getDescripcionNovedadActualizacion() {
        return this.descripcionNovedadActualizacion;
    }
    
    public void setDescripcionNovedadActualizacion(String descripcionNovedadActualizacion) {
        this.descripcionNovedadActualizacion = descripcionNovedadActualizacion;
    }

    
    @Column(name="descripcionDosNovedad", length=100)
    public String getDescripcionDosNovedad() {
        return this.descripcionDosNovedad;
    }
    
    public void setDescripcionDosNovedad(String descripcionDosNovedad) {
        this.descripcionDosNovedad = descripcionDosNovedad;
    }

    
    @Column(name="usuarioRegActualizacion", length=10)
    public String getUsuarioRegActualizacion() {
        return this.usuarioRegActualizacion;
    }
    
    public void setUsuarioRegActualizacion(String usuarioRegActualizacion) {
        this.usuarioRegActualizacion = usuarioRegActualizacion;
    }




}


