package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="perfil"
    ,catalog="gestor_versiones"
)
public class Perfil  implements java.io.Serializable {


     private String pkIdPerfil;
     private String descripcionPerfil;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String pkIdPerfil, String descripcionPerfil) {
        this.pkIdPerfil = pkIdPerfil;
        this.descripcionPerfil = descripcionPerfil;
    }
    public Perfil(String pkIdPerfil, String descripcionPerfil, Set usuarios) {
       this.pkIdPerfil = pkIdPerfil;
       this.descripcionPerfil = descripcionPerfil;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="pk_idPerfil", unique=true, nullable=false, length=20)
    public String getPkIdPerfil() {
        return this.pkIdPerfil;
    }
    
    public void setPkIdPerfil(String pkIdPerfil) {
        this.pkIdPerfil = pkIdPerfil;
    }

    
    @Column(name="descripcionPerfil", nullable=false, length=60)
    public String getDescripcionPerfil() {
        return this.descripcionPerfil;
    }
    
    public void setDescripcionPerfil(String descripcionPerfil) {
        this.descripcionPerfil = descripcionPerfil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


