package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="gestor_versiones"
)
public class Usuario  implements java.io.Serializable {


     private String pkIdUsuario;
     private Perfil perfil;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String contrasena;
     private Set usuarioTieneAplicacions = new HashSet(0);

    public Usuario() {
        this.perfil= new Perfil();
    }

	
    public Usuario(String pkIdUsuario, Perfil perfil, String nombreUsuario, String apellidoUsuario, String contrasena) {
        this.pkIdUsuario = pkIdUsuario;
        this.perfil = perfil;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.contrasena = contrasena;
    }
    public Usuario(String pkIdUsuario, Perfil perfil, String nombreUsuario, String apellidoUsuario, String contrasena, Set usuarioTieneAplicacions) {
       this.pkIdUsuario = pkIdUsuario;
       this.perfil = perfil;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.contrasena = contrasena;
       this.usuarioTieneAplicacions = usuarioTieneAplicacions;
    }
   
     @Id 

    
    @Column(name="pk_idUsuario", unique=true, nullable=false, length=10)
    public String getPkIdUsuario() {
        return this.pkIdUsuario;
    }
    
    public void setPkIdUsuario(String pkIdUsuario) {
        this.pkIdUsuario = pkIdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario_perfil", nullable=false)
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="nombreUsuario", nullable=false, length=20)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="apellidoUsuario", nullable=false, length=20)
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }

    
    @Column(name="contrasena", nullable=false, length=32)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getUsuarioTieneAplicacions() {
        return this.usuarioTieneAplicacions;
    }
    
    public void setUsuarioTieneAplicacions(Set usuarioTieneAplicacions) {
        this.usuarioTieneAplicacions = usuarioTieneAplicacions;
    }




}


