package ec.fe.gv.modelo;
// Generated Jul 25, 2014 12:27:28 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioTieneAplicacion generated by hbm2java
 */
@Entity
@Table(name="usuario_tiene_aplicacion"
    ,catalog="gestor_versiones"
)
public class UsuarioTieneAplicacion  implements java.io.Serializable {


     private Integer pkIdUsuarioAplicacion;
     private Usuario usuario;
     private Aplicacion aplicacion;

    public UsuarioTieneAplicacion() {
        this.aplicacion = new Aplicacion();
        this.usuario = new Usuario();
    }

    public UsuarioTieneAplicacion(Usuario usuario, Aplicacion aplicacion) {
       this.usuario = usuario;
       this.aplicacion = aplicacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pk_idUsuarioAplicacion", unique=true, nullable=false)
    public Integer getPkIdUsuarioAplicacion() {
        return this.pkIdUsuarioAplicacion;
    }
    
    public void setPkIdUsuarioAplicacion(Integer pkIdUsuarioAplicacion) {
        this.pkIdUsuarioAplicacion = pkIdUsuarioAplicacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario_tiene_aplicacion_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuario_tiene_aplicacion_aplicacion", nullable=false)
    public Aplicacion getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(Aplicacion aplicacion) {
        this.aplicacion = aplicacion;
    }




}


